name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:
  push:
    branches: ["main", "test"] # Track both main and test branches
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vikashegde21
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 21
          plugin_languages_recent_load: 500
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%

          plugin_activity: yes
          plugin_activity_days: 21
          plugin_activity_filter: all
          plugin_activity_limit: 10

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic

          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_sort: stars